In [12]:
import os
cur_dir = os.getcwd()
from utils.processing_utils import mi_edge_index_batched

mi_dict_path = os.path.join(cur_dir, 'data_tensor_cache', 'data', 'mi_dict_static.pickle')
batch_size = 3
num_nodes = 60

edge_index = mi_edge_index_batched(batch_size=batch_size, num_nodes=num_nodes, mi_dict_path=mi_dict_path)
edge_index

tensor([[  0,   0,   0,  ..., 359, 359, 359],
        [  1,   2,   3,  ..., 354, 355, 356]])

In [13]:
edge_index.shape

torch.Size([2, 2856])

In [14]:
ad_edge_index = edge_index[:, :476]
dis_edge_index = edge_index[:, 476:]

In [15]:
dis_edge_index.unique()

tensor([ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 102,
        104, 105, 106, 107, 108, 111, 114, 115, 116, 117, 118, 119, 120, 121,
        122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
        136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 162, 164, 165,
        166, 167, 168, 171, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
        184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
        198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
        212, 213, 214, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227,
        228, 231, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
        246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 2

In [16]:
import torch
a = torch.arange(0, 180)
b = a + 180

len_a = a.shape[0]
len_b = b.shape[0]

a = a.view(-1, len_a)
b = b.view(-1, len_b)

edge_index_2 = torch.cat((a, b), dim=0)


In [17]:
edge_index_2[:, 1]

tensor([  1, 181])

In [18]:
import torch
a = torch.arange(0, 180)
b = a + 180

a = a.unsqueeze(dim=0)
b = b.unsqueeze(dim=0)

print(a.shape)
new_edge = torch.cat((a, b), dim = 0)

torch.Size([1, 180])


In [19]:
torch.cat((edge_index, new_edge), dim = 1).shape

torch.Size([2, 3036])

In [20]:
3036 - 2856

180

In [21]:
from teds_tensor_dataset import TEDSTensorDataset
root = os.path.join(cur_dir, 'data_tensor_cache')
dataset = TEDSTensorDataset(root)

저장되어 있는 전처리된 데이터가 없으므로, 전처리 과정을 진행합니다. 전처리된 데이터는 저장됩니다.
저장 경로: /Users/jeong-yunseong/Documents/programming/Phase_2/data_tensor_cache/process/processed_data.pt
전처리 완료
불러오기 완료
전처리된 데이터 저장 완료


In [22]:
dataset.LOS.unique()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37])